import type { Metadata } from 'next';
import { Page, PageHeader, Section } from '@/components/system/primitives';

export const metadata: Metadata = {
  title: 'Legal',
  description: 'Privacy, terms and disclaimers for VESTRIPPN.',
};

const UPDATED = 'October 9, 2026';

const SECTIONS = [
  { id: 'overview', label: 'Overview' },
  { id: 'privacy', label: 'Privacy Policy' },
  { id: 'data', label: 'Data We Process' },
  { id: 'cookies', label: 'Cookies & Local Storage' },
  { id: 'sharing', label: 'Third Parties' },
  { id: 'rights', label: 'Your Choices & Rights' },
  { id: 'security', label: 'Security & Retention' },
  { id: 'terms', label: 'Terms of Use' },
  { id: 'medical', label: 'Medical Disclaimer' },
  { id: 'contact', label: 'Contact' },
];

export default function LegalPage() {
  return (
    <Page>
      <PageHeader
        label="legal"
        title="Privacy, terms & disclaimers"
        lede="VESTRIPPN is a personal, cloud-integrated platform for medical study, research, fitness and workflow automation. This page explains what data it processes and how."
        meta={[{ key: 'last updated', value: UPDATED }]}
      />
      <nav aria-label="Contents" className="sys-inline-links" style={{ marginTop: 24 }}>
        {SECTIONS.map((section) => (
          <a key={section.id} href={`#${section.id}`}>
            {section.label.toLowerCase()}
          </a>
        ))}
      </nav>
      <div className="sys-legal">
              <Section id="overview" title="Overview">
                <P>VESTRIPPN (&ldquo;the platform&rdquo;, &ldquo;we&rdquo;, &ldquo;us&rdquo;) is operated as a personal project by its sole operator. Its portfolio pages, IELTS practice and clinical case practice are public; the study and research tools are built for the operator&rsquo;s own academic and operational use and require sign-in. By accessing the platform you agree to the practices and terms below.</P>
                <P>If you do not agree with any part of this document, please discontinue use. We may update this page from time to time; the &ldquo;Last updated&rdquo; date above reflects the current version.</P>
              </Section>

              <Section id="privacy" title="Privacy Policy">
                <P>We collect only the data needed to run the platform&rsquo;s features and to keep your account secure. We do not sell personal data, and we do not use it for advertising.</P>
                <H>Account &amp; authentication</H>
                <Ul items={[
                  'Sign-in is handled by NextAuth. You may authenticate with Google, LINE, or an email-and-password credential.',
                  'For social sign-in we receive your name, email address, profile image, and a provider account identifier from Google or LINE.',
                  'For email-and-password sign-in, your password is stored only as a salted hash — never in plain text.',
                  'Session and account records are kept to keep you signed in and to associate your data with your account.',
                ]} />
              </Section>

              <Section id="data" title="Data We Process">
                <P>Depending on which features you use, the platform may store the following in its database:</P>
                <Ul items={[
                  'Academic telemetry — tasks, daily command notes, exam/milestone tracking, Canvas-derived subjects and metrics, and IELTS modules and items.',
                  'Spaced-repetition stats — Anki review counts, due/new cards, and streaks you sync or enter.',
                  'Research data — saved literature extractions, DOIs and citation details, and research project records.',
                  'Clinical study data — clinical case progress, attempts, and usage counts for learning features.',
                  'Fitness logs — training entries and streak data you record.',
                  'AI assistant content — chat threads and messages when you ask questions of your uploaded documents, and a record of each assistant request (time, model and token counts) used to apply the usage limit.',
                  'Notifications and study documents you create or upload, including extracted text chunks used for search.',
                ]} />
                <P>This data is provided by you or generated by your activity. You may choose not to use a feature, in which case its data is not created. Visitors who are not signed in can browse the public pages and use the practice questions and clinical cases; their answers and case progress are not saved.</P>
              </Section>

              <Section id="cookies" title="Cookies & Local Storage">
                <P>We use a small number of strictly necessary cookies to keep you signed in (session and authentication cookies set by NextAuth). These are required for the platform to function and are not used for tracking or advertising.</P>
                <P>Your browser&rsquo;s local storage holds your display preferences on your device only — for example the selected livery, day/night mode, low-power mode, and Focus-Mode personal-best lap times. This information stays in your browser and is not transmitted to the server.</P>
              </Section>

              <Section id="sharing" title="Third Parties">
                <P>The platform relies on a few service providers to deliver its features. Data is shared with them only to the extent needed for the relevant function:</P>
                <Ul items={[
                  'Identity providers (Google, LINE) — used only to authenticate you.',
                  'Hosting and database infrastructure — used to run the application and store your records securely.',
                  'AI provider (OpenAI) — powers the assistant. When you use it, your question, earlier messages in the conversation and the data of the area you ask about (for example tasks, exam dates, Canvas assignments or Anki statistics) are sent to OpenAI. Documents you upload are sent to create search embeddings, and the passages used for an answer are sent with your question. Nothing is sent unless you use these features.',
                  'Research data sources (e.g. PubMed, Europe PMC, Crossref, Scopus, ScienceDirect, Scholar, ClinicalKey) and your learning-management system (Canvas) — queried to retrieve the information you request.',
                ]} />
                <P>Each provider handles data under its own terms and privacy policy. We do not share your personal data with third parties for their own marketing.</P>
              </Section>

              <Section id="rights" title="Your Choices & Rights">
                <P>You can review and manage much of your information directly inside the platform. You may also request to access, correct, export, or delete the personal data associated with your account, and you can withdraw consent or close your account at any time.</P>
                <P>To make a request, use the contact details below. We will respond within a reasonable time and may need to verify your identity first.</P>
              </Section>

              <Section id="security" title="Security & Retention">
                <P>We apply reasonable technical and organizational measures to protect your data, including encrypted transport (HTTPS), hashed passwords, and access controls. No method of transmission or storage is completely secure, so we cannot guarantee absolute security.</P>
                <P>We retain data for as long as your account is active or as needed to provide the platform. When data is no longer required, or upon a valid deletion request, we remove it or anonymize it.</P>
              </Section>

              <Section id="terms" title="Terms of Use">
                <Ul items={[
                  'The platform is provided on an “as is” and “as available” basis, without warranties of any kind. To the maximum extent permitted by law, the operator is not liable for any damages arising from its use.',
                  'You are responsible for activity under your account and for keeping your credentials secure.',
                  'Use the platform lawfully. Do not attempt to disrupt it, access other users’ data, reverse-engineer it, or misuse its automation or AI features.',
                  'All branding, code, design, and original content are the property of the operator unless otherwise noted. Third-party names, trademarks, and data belong to their respective owners.',
                  'We may modify, suspend, or discontinue any part of the platform, and may update these terms, at any time. Continued use after changes means you accept the updated terms.',
                ]} />
              </Section>

              <Section id="medical" title="Medical Disclaimer">
                <P>The platform includes medical study material such as clinical cases, mock exams, and reference content. This material is for education and personal study only. It is <strong>not medical advice</strong> and must not be used to diagnose, treat, or make decisions about any real patient.</P>
                <P>AI-assisted outputs can be incomplete or incorrect and should always be verified against authoritative clinical sources and professional judgment. Always defer to qualified supervisors, institutional guidelines, and licensed clinical practice.</P>
              </Section>

              <Section id="contact" title="Contact">
                <P>Questions about privacy, your data, or these terms can be sent to the platform operator. For data requests, please describe what you would like to access, correct, export, or delete.</P>
                <p className="sys-mono" style={{ marginTop: 12 }}>
                  operator contact · <a href="mailto:ativich_2549@yahoo.com">ativich_2549@yahoo.com</a>
                </p>
              </Section>

              <p className="sys-section-intro" style={{ marginTop: 48 }}>
                This document is provided for transparency and is not legal advice. For a binding policy tailored to your jurisdiction and obligations, have it reviewed by a qualified professional.
              </p>

      </div>
    </Page>
  );
}

function P({ children }: { children: React.ReactNode }) {
  return <p>{children}</p>;
}

function H({ children }: { children: React.ReactNode }) {
  return <h3 className="sys-label">{children}</h3>;
}

function Ul({ items }: { items: string[] }) {
  return (
    <ul>
      {items.map((item) => (
        <li key={item.slice(0, 32)}>{item}</li>
      ))}
    </ul>
  );
}
